# The YAML contains definitions of inputs of the composite GitHub Action.
name: "Comment to the merged pull request"
description: "Create a comment to the merged pull request"

branding:
  icon: "code"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  message:
    description: |-
      The message to be commented to the merged pull request.
      Back quotes aren't allowed, because that causes a syntax error of the github-script action.
    required: true

outputs:
  pull-request-number:
    description: "The pull request number of the pull request created by the composite GitHub Action"
    value: ${{ steps.get_pr_number.outputs.result }}
  pull-request-creator:
    description: "The GitHub account name who created the pull request"
    value: ${{ steps.get_pr_creator.outputs.result }}


runs:
  using: "composite"
  steps:
    - name: "Get the commit hash of the merged pull request"
      id: get_commit_hash
      shell: bash
      run: |
        echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    # Get the pull request number from the commit hash using github-script
    - name: "Search the pull request number by the commit hash of the merged pull request"
      id: get_pr_number
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        script: |
          const commit_hash = "${{ steps.get_commit_hash.outputs.commit_hash }}";
          const { data: { items } } = await github.rest.search.issuesAndPullRequests({
            q: `${commit_hash} type:pr is:merged`
          });
          const pr_number = items[0].number;
          console.log(`The pull request number is ${pr_number}`);
          return pr_number;
    # Get the GitHub account name who created the merged pull request by the pull request number
    - name: "Get the GitHub account name who created the merged pull request"
      id: get_pr_creator
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        result-encoding: string
        script: |
          const pr_number = "${{ steps.get_pr_number.outputs.result }}";
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number
          });
          const pr_creator = pr.data.user.login;
          console.log(`The GitHub account name who created the merged pull request is ${pr_creator}`);
          return pr_creator;
    # Create a comment to the merged pull request
    - name: "Comment to the merged pull request"
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        debug: true
        script: |
          const pr_number = "${{ steps.get_pr_number.outputs.result }}";
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr_number,
            body: `@${{ steps.get_pr_creator.outputs.result }}
            ${{ inputs.message }}`
          });
          console.log(`Commented to the pull request ${pr_number}`);
