name: Test the action in a pull request

on:
  pull_request: {}

permissions: read-all

jobs:
  comment:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # We have to check out the default branch before using the action.
      - uses: actions/checkout@v4
      # The step is triggered only when dummy-failed-step is failed.
      - uses: ./
        id: merged-pr-info
        with:
          is_merged: "0"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |-
            The testing of the action in a pull request was successful.
